### ISSUE TITLE
Regional Switch Vendors

### ISSUE THREAD

**Issue by Dingo-Seven** [Dingo-Seven/Keebort-Resources#2]
Looking for regional switch vendors comparable to what Milktooth is for North Americans.

Looking for the following regions:
- Latin America/South America
- Europe
- Asia
- Australia

Thanks in advance lads, much appreciated

**Comment by diego-ruben-cruz** [comment]
Possible switch vendor for EU-ASIA: https://rationalkeys.com.tr/

Requires further research

**Comment by Dingo-Seven** [comment]
Some more possible switch vendors for EU:
- Monacokeys (GER)
- Keygem (GER)
- Deltakeyco (FRA)
- EloquentClicks (SPA)
- CoffeeKeys (ITA)
- MaxGaming (SWE)

Requires further research

**Comment by Dingo-Seven** [comment]
Added links to Alexotos and MKtrust to useful links master bibliography among a few others

Unsure of creating my own list with ratings, seeing as there are almost no similar outlets for switches comparable to Milktooth.

**Comment by diego-ruben-cruz** [comment]
Decided to not continue with maintaining a vendor list, will instead document several other vendor lists from different sources with their own judgement system.
